#!/usr/bin/env python3
"""
Makes the emoji the client draws and both sides know of (phase 10):

  src/client/assets/NotoEmoji.ttf     Google's single-colour Noto Emoji
                                      font, at a semi-bold weight (600), which reads better at text size, and cut
                                      down to the emoji below
  src/common/proto/emoji_table.odin   those emoji: the character, its
                                      shortcodes and its category

The emoji are GitHub's gemoji list (MIT), those that are one character
(once a variation selector is dropped, as yap's text does), and that the
font has a glyph for. Sequences (flags, skin tones, people joined with
U+200D) are left out: the text sanitizer drops the joiners, and the font
would need shaping to draw them.

Both outputs are committed; this is only run to bring them up to date.
It needs Python 3 with fontTools, and fetches its inputs with curl.

	scripts/emoji.py
"""

import json
import os
import subprocess
import sys
import tempfile

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

FONT_URL = "https://github.com/google/fonts/raw/main/ofl/notoemoji/NotoEmoji%5Bwght%5D.ttf"
LIST_URL = "https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json"

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_OUT = os.path.join(ROOT, "src/client/assets/NotoEmoji.ttf")
TABLE_OUT = os.path.join(ROOT, "src/common/proto/emoji_table.odin")

# gemoji's categories, as the table's enum names them, in picker order.
CATEGORIES = {
    "Smileys & Emotion": "Smileys",
    "People & Body": "People",
    "Animals & Nature": "Animals",
    "Food & Drink": "Food",
    "Travel & Places": "Travel",
    "Activities": "Activities",
    "Objects": "Objects",
    "Symbols": "Symbols",
    "Flags": "Flags",
}


def fetch(url, path):
    subprocess.run(["curl", "-sSfL", "-o", path, url], check=True)


def main():
    with tempfile.TemporaryDirectory() as tmp:
        font_path = os.path.join(tmp, "font.ttf")
        list_path = os.path.join(tmp, "emoji.json")
        fetch(FONT_URL, font_path)
        fetch(LIST_URL, list_path)

        font = TTFont(font_path)
        cmap = font.getBestCmap()
        entries = []
        seen = set()
        for e in json.load(open(list_path, encoding="utf-8")):
            chars = e["emoji"].replace("️", "")
            if len(chars) != 1:
                continue
            r = ord(chars)
            if r in seen or r not in cmap or not e["aliases"]:
                continue
            seen.add(r)
            names = [a for a in e["aliases"] if all(c.isalnum() or c in "_+-" for c in a)]
            if not names:
                continue
            entries.append((r, " ".join(names), CATEGORIES[e["category"]]))

        regular = instancer.instantiateVariableFont(font, {"wght": 600})
        options = subset.Options()
        options.layout_features = []
        options.hinting = False
        options.notdef_outline = True
        options.name_IDs = ["*"]
        options.drop_tables += ["GSUB", "GPOS", "GDEF", "STAT"]
        subsetter = subset.Subsetter(options)
        subsetter.populate(unicodes=[r for r, _, _ in entries])
        subsetter.subset(regular)
        regular.save(FONT_OUT)

    with open(TABLE_OUT, "w", encoding="utf-8") as out:
        out.write("// Generated by scripts/emoji.py from GitHub's gemoji list (MIT):\n")
        out.write("// see src/client/licenses/gemoji.txt. Don't edit; run the script.\n")
        out.write("package proto\n\n")
        out.write("Emoji_Category :: enum u8 {\n")
        for name in CATEGORIES.values():
            out.write("\t%s,\n" % name)
        out.write("}\n\n")
        out.write("// The emoji there are, in picker order: the character, its shortcodes\n")
        out.write("// (the first is its name), and its category.\n")
        out.write("@(rodata)\nEMOJI := [?]Emoji{\n")
        for r, names, category in entries:
            out.write('\t{0x%X, "%s", .%s},\n' % (r, names, category))
        out.write("}\n\n")
        out.write("// The same characters in order, with where each is in EMOJI, to look\n")
        out.write("// one up (emoji_index).\n")
        out.write("@(rodata)\nEMOJI_BY_RUNE := [?]Emoji_Ref{\n")
        for i, (r, _, _) in sorted(enumerate(entries), key=lambda e: e[1][0]):
            out.write("\t{0x%X, %d},\n" % (r, i))
        out.write("}\n")
    print("%d emoji; font %d bytes" % (len(entries), os.path.getsize(FONT_OUT)), file=sys.stderr)


main()
